# Generated by Django 4.1.4 on 2023-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_class', models.IntegerField(verbose_name='工具类型')),
                ('tool_price', models.FloatField(verbose_name='工具价格')),
                ('tool_part', models.IntegerField(verbose_name='工具所属部门')),
                ('tool_area', models.IntegerField(verbose_name='工具所属区域')),
                ('tool_borrowed', models.BooleanField(default=False, verbose_name='工具是否被借出')),
                ('tool_damaged', models.BooleanField(default=False, verbose_name='工具是否损坏')),
            ],
        ),
    ]
