# Generated by Django 4.1.7 on 2023-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="tool_name",
            field=models.CharField(default="", max_length=255, verbose_name="工具名称"),
        ),
    ]
